service: ufoe-lunchbot

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: prod
  exclude:
    - .idea/**
    - lunchbot.iml
    - node_modules/**
    - .serverless/**

functions:
  getAllLunchMenus:
    handler: handler.get_all_dishes
    events:
      - http:
          path: lunch/today
          method: get
